apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    io.kompose.service: app
  ports:
    - port: 2283
      targetPort: 2283
      nodePort: {{ .Values.nodePort }}
