apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
type: Opaque
data:
  DB_PASSWORD: {{ required "db.password is required" .Values.db.password | b64enc | quote }}
  TUNNEL_TOKEN: {{ required "cloudflareTunnelToken is required" .Values.cloudflareTunnelToken | b64enc | quote }}
